import type { Metadata } from "next";
import { Noto_Sans_Display } from "next/font/google";
import { Header } from "src/components/Header/Header";
import { Footer } from "src/components/Footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          <div className="container">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
