import type { Metadata } from "next";
import { Noto_Sans_Display } from "next/font/google";
import { Header } from "src/components/Header/Header";
import "./globals.css";
import { Footer } from "src/components/Footer/Footer";

const inter = Noto_Sans_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
