name: CI/CD MAIN_FRONT_END

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Start App
        run: pm2 restart fonates.front
        # restart the app